name: Build and Test

on: [push, pull_request]

jobs:

  test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-feature=2020-resolver -r requirements.txt

    - name: Build package
      run: tools/build-wheel.sh
      shell: bash

    - name: Install package
      run: pip install -U assets/dist/tflite2onnx-*.whl

    - name: Testing (collecting coverage data)
      run: coverage run --source=./tflite2onnx -m pytest

    # - name: SSH via Ngrok if fail
    #   if: ${{ failure() }}
    #   env:
    #     # Find token in: https://dashboard.ngrok.com/get-started/setup
    #     NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    #     NGROK_LOCAL_PASS: ${{ secrets.NGROK_LOCAL_PASS }}
    #   run: tools/open-github-connection.sh
    # - name: Live instance if fail
    #   if: ${{ failure() }}
    #   run: sleep 1h

    - name: Uploading coverage report
      continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        coverage xml
        bash <(curl -s https://codecov.io/bash)
